### ISSUE TITLE
Stream.Read may return less than requested bytes

### ISSUE THREAD

**Issue by ddrinka** [goldenbull/ManagedXZ#6]
Reading through the source, I noticed the following:
https://github.com/goldenbull/ManagedXZ/blob/master/src/ManagedXZ/XZDecompressStream.cs#L82

Stream.Read may return less than the requested bytes for any number of reasons, not only when it has reached the end of a Stream.

For instance, NetworkStream will return the number of bytes currently available, even if that's less than the number requested.  Zero bytes is the only special case, which indicates EndOfStream.

I think you should just check for zero here and send LZMA_FINISH in that case.  Otherwise just push through whatever data you got from the Read.

**Comment by goldenbull** [comment]
Yes you are right, thanks for your remind.

**Comment by goldenbull** [comment]
fixed https://github.com/goldenbull/ManagedXZ/commit/ae42f17b29509eed20a01ba6794a23d2fe7565e8#diff-04732c5b27468a8efc0fa8bfd64cf01eR82
