### ISSUE TITLE
Support for directories.

### ISSUE THREAD

**Issue by TesterTestingVirtualMachines** [goldenbull/ManagedXZ#7]
Hello, so I'm trying to create an compression program that uses XZ format. The other ones I saw used LZMA, which doesn't support multithreading. However, I'm not sure how to make use of this for directories, I only know how to use this for files.
Any help would be appreciated, thanks.

**Comment by goldenbull** [comment]
this is just a simple wrapper of C++ xz utils which supports single file (more accurately, stream) only.
you can try other feature-complete packages like 7z or sharpzip etc :-)
