### ISSUE TITLE
Feature request: Use ArrayPool instead of creating new byte[] every time.

### ISSUE THREAD

**Issue by zgabi** [goldenbull/ManagedXZ#8]
Hi,

Please use System.Buffers.ArrayPool<byte> to get a new buffer in the following lines:
https://github.com/goldenbull/ManagedXZ/blob/09b2d9deb7c5b24ac716681d3e2095d8c6a64b46/src/ManagedXZ/XZDecompressStream.cs#L80

https://github.com/goldenbull/ManagedXZ/blob/09b2d9deb7c5b24ac716681d3e2095d8c6a64b46/src/ManagedXZ/XZCompressStream.cs#L142

https://github.com/goldenbull/ManagedXZ/blob/09b2d9deb7c5b24ac716681d3e2095d8c6a64b46/src/ManagedXZ/XZCompressStream.cs#L169

And maybe in the XZUtils.

They are just temporary buffers, and can be returned in the end of the code block with: `ArrayPool<byte>.Shared.Return(data);`

Thank you.

**Comment by goldenbull** [comment]
ArrayPool is only available in dotnet core, not supported by dotnet framework. I will see if I can use predefined compiler macros to switch between them.

**Comment by zgabi** [comment]
It is available in. Net 4.5+

See the official nuget package: https://www.nuget.org/packages/System.Buffers/

**Comment by zgabi** [comment]
Any news on this issue?

**Comment by zgabi** [comment]
Project is dead, created a fork which contains this fix.
